In [3]:
%matplotlib notebook

In [4]:
from textwrap import wrap
import psycopg2
import pandas as pd
import sqlalchemy
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import rcParams
from sqlalchemy import create_engine

In [5]:
# Necessary Postgres login information
connection_string = "postgres:postgres@localhost:5432/2017_StreamingDB"
# Create the connection
engine = create_engine(f'postgresql://{connection_string}')

In [54]:
Top_BB = pd.read_sql_query('''SELECT *  FROM top_billboard WHERE rank < '11';''', engine)
Top_BB.set_index(('rank'), inplace=True)
#Rename Columns and Drop Columns
Top_BB['Track_by_Artist']= Top_BB['track'].values + ' - ' + Top_BB['artist']
Top_BB

,track,artist,Track_by_Artist
rank,,,
1,Despacito,Luis Fonsi & Daddy Yankee Featuring Justin Bieber,Despacito - Luis Fonsi & Daddy Yankee Featurin...
2,Shape Of You,Ed Sheeran,Shape Of You - Ed Sheeran
3,Bad And Boujee,Migos Featuring Lil Uzi Vert,Bad And Boujee - Migos Featuring Lil Uzi Vert
4,Humble.,Kendrick Lamar,Humble. - Kendrick Lamar
5,That's What I Like,Bruno Mars,That's What I Like - Bruno Mars
6,Congratulations,Post Malone Featuring Quavo,Congratulations - Post Malone Featuring Quavo
7,XO TOUR Llif3,Lil Uzi Vert,XO TOUR Llif3 - Lil Uzi Vert
8,Mask Off,Future,Mask Off - Future
9,Closer,The Chainsmokers Featuring Halsey,Closer - The Chainsmokers Featuring Halsey
10,I'm The One,"DJ Khaled Featuring Justin Bieber, Quavo, Chan...",I'm The One - DJ Khaled Featuring Justin Biebe...

In [46]:
All_df = pd.read_sql_query('''SELECT artist, track,SUM (streams) FROM top_spotify GROUP BY artist,track;''', engine)
All_df = All_df.sort_values('sum', ascending=False)
All_df['spotify_rank'] = range(1, 1+len(All_df))
All_df.set_index(("spotify_rank"), inplace=True)
# All_df['Track_by_Artist']= All_df['track'].values + ' - ' + All_df['artist']
# All_df = All_df[['artist','track','spotify_rank','streams']]
All_df.head(10)

                        artist                     track        sum
spotify_rank
1                   Ed Sheeran              Shape of You  672625163
2                   Luis Fonsi         Despacito - Remix  436357471
3               Kendrick Lamar                   HUMBLE.  427988388
4                 Lil Uzi Vert             XO TOUR Llif3  385291739
5                  Post Malone                  rockstar  360260253
6                  Post Malone           Congratulations  345297028
7               French Montana             Unforgettable  343472485
8                    DJ Khaled               I'm the One  330539999
9                       Future                  Mask Off  330301606
10            The Chainsmokers  Something Just Like This  326179128

In [48]:
FR_df = pd.read_sql_query('''SELECT * FROM top_spotify WHERE region = 'fr' ORDER BY streams DESC;''', engine)
FR_df['fr_rank'] = range(1, 1+len(FR_df))
FR_df.set_index(("fr_rank"), inplace=True)
# FR_df

In [49]:
DE_df = pd.read_sql_query('''SELECT * FROM top_spotify WHERE region = 'de' ORDER BY streams DESC;''', engine)
DE_df['de_rank'] = range(1, 1+len(DE_df))
DE_df.set_index(("de_rank"), inplace=True)

In [50]:
US_df = pd.read_sql_query('''SELECT * FROM top_spotify WHERE region = 'us' ORDER BY streams DESC;''', engine)
US_df['us_rank'] = range(1, 1+len(US_df))
US_df.set_index(("us_rank"), inplace=True)

In [51]:
LT_df = pd.read_sql_query('''SELECT * FROM top_spotify WHERE region = 'lt' ORDER BY streams DESC;''', engine)
LT_df['lt_rank'] = range(1, 1+len(LT_df))
LT_df.set_index(("lt_rank"), inplace=True)

In [52]:
NO_df = pd.read_sql_query('''SELECT * FROM top_spotify WHERE region = 'no' ORDER BY streams DESC;''', engine)
NO_df['no_rank'] = range(1, 1+len(NO_df))
NO_df.set_index(("no_rank"), inplace=True)